name: my_application_with_dart_library
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

publish_to: none

# Add regular dependencies here.
dependencies:
  my_first_packages_library:
    git:
      url: git@github.com:sumitroajiprabowo/my_first_packages_library.git
      ref: 1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
